import { describe, expect, it } from 'vitest';
import {
  ensureRouteGroupingSchemaCompatibility,
  type RouteGroupingSchemaInspector,
} from './routeGroupingSchemaCompatibility.js';

function createInspector(
  dialect: RouteGroupingSchemaInspector['dialect'],
  options?: {
    existingColumnsByTable?: Partial<Record<'token_routes' | 'route_channels', string[]>>;
    existingTables?: Array<'token_routes' | 'route_channels' | 'route_group_sources' | 'route_channel_stat_snapshots'>;
  },
) {
  const executedSql: string[] = [];
  const existingTables = new Set(options?.existingTables ?? ['token_routes', 'route_channels']);
  const existingColumnsByTable = {
    token_routes: new Set(options?.existingColumnsByTable?.token_routes ?? []),
    route_channels: new Set(options?.existingColumnsByTable?.route_channels ?? []),
  };

  const inspector: RouteGroupingSchemaInspector = {
    dialect,
    async tableExists(table) {
      return existingTables.has(table as 'token_routes' | 'route_channels' | 'route_group_sources' | 'route_channel_stat_snapshots');
    },
    async columnExists(table, column) {
      if (table === 'token_routes' || table === 'route_channels') {
        return existingColumnsByTable[table].has(column);
      }
      return false;
    },
    async execute(sqlText) {
      executedSql.push(sqlText);
    },
  };

  return { inspector, executedSql };
}

describe('ensureRouteGroupingSchemaCompatibility', () => {
  it.each([
    {
      dialect: 'sqlite' as const,
      expectedSql: [
        'CREATE TABLE IF NOT EXISTS route_group_sources (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, group_route_id integer NOT NULL REFERENCES token_routes(id) ON DELETE cascade, source_route_id integer NOT NULL REFERENCES token_routes(id) ON DELETE cascade);',
        'CREATE UNIQUE INDEX IF NOT EXISTS route_group_sources_group_source_unique ON route_group_sources(group_route_id, source_route_id);',
        'CREATE INDEX IF NOT EXISTS route_group_sources_source_route_id_idx ON route_group_sources(source_route_id);',
        'CREATE TABLE IF NOT EXISTS route_channel_stat_snapshots (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, identity_key text NOT NULL, model_pattern text NOT NULL, account_id integer NOT NULL, token_id integer, oauth_route_unit_id integer, source_model text, success_count integer DEFAULT 0, fail_count integer DEFAULT 0, total_latency_ms integer DEFAULT 0, total_cost real DEFAULT 0, total_input_tokens integer DEFAULT 0, last_used_at text, last_selected_at text, last_fail_at text, consecutive_fail_count integer NOT NULL DEFAULT 0, cooldown_level integer NOT NULL DEFAULT 0, cooldown_until text, created_at text DEFAULT (datetime(\'now\')), updated_at text DEFAULT (datetime(\'now\')));',
        'CREATE UNIQUE INDEX IF NOT EXISTS route_channel_stat_snapshots_identity_unique ON route_channel_stat_snapshots(identity_key);',
        'CREATE INDEX IF NOT EXISTS route_channel_stat_snapshots_model_pattern_idx ON route_channel_stat_snapshots(model_pattern);',
        'CREATE INDEX IF NOT EXISTS route_channel_stat_snapshots_account_id_idx ON route_channel_stat_snapshots(account_id);',
        'CREATE INDEX IF NOT EXISTS route_channel_stat_snapshots_token_id_idx ON route_channel_stat_snapshots(token_id);',
        'CREATE INDEX IF NOT EXISTS route_channel_stat_snapshots_oauth_route_unit_id_idx ON route_channel_stat_snapshots(oauth_route_unit_id);',
        'ALTER TABLE token_routes ADD COLUMN display_name text;',
        'ALTER TABLE token_routes ADD COLUMN display_icon text;',
        'ALTER TABLE token_routes ADD COLUMN route_mode text DEFAULT \'pattern\';',
        'ALTER TABLE token_routes ADD COLUMN decision_snapshot text;',
        'ALTER TABLE token_routes ADD COLUMN decision_refreshed_at text;',
        'ALTER TABLE token_routes ADD COLUMN routing_strategy text DEFAULT \'weighted\';',
        'ALTER TABLE route_channels ADD COLUMN source_model text;',
        'ALTER TABLE route_channels ADD COLUMN last_selected_at text;',
        'ALTER TABLE route_channels ADD COLUMN consecutive_fail_count integer NOT NULL DEFAULT 0;',
        'ALTER TABLE route_channels ADD COLUMN cooldown_level integer NOT NULL DEFAULT 0;',
        'ALTER TABLE route_channels ADD COLUMN total_input_tokens integer DEFAULT 0;',
        'ALTER TABLE route_channels ADD COLUMN image_upscale_enabled integer DEFAULT 0;',
      ],
    },
    {
      dialect: 'postgres' as const,
      expectedSql: [
        'CREATE TABLE IF NOT EXISTS "route_group_sources" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, "group_route_id" INTEGER NOT NULL, "source_route_id" INTEGER NOT NULL, CONSTRAINT "route_group_sources_group_route_id_token_routes_id_fk" FOREIGN KEY ("group_route_id") REFERENCES "token_routes"("id") ON DELETE CASCADE, CONSTRAINT "route_group_sources_source_route_id_token_routes_id_fk" FOREIGN KEY ("source_route_id") REFERENCES "token_routes"("id") ON DELETE CASCADE)',
        'CREATE UNIQUE INDEX IF NOT EXISTS "route_group_sources_group_source_unique" ON "route_group_sources" ("group_route_id", "source_route_id")',
        'CREATE INDEX IF NOT EXISTS "route_group_sources_source_route_id_idx" ON "route_group_sources" ("source_route_id")',
        'CREATE TABLE IF NOT EXISTS "route_channel_stat_snapshots" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, "identity_key" TEXT NOT NULL, "model_pattern" TEXT NOT NULL, "account_id" INTEGER NOT NULL, "token_id" INTEGER, "oauth_route_unit_id" INTEGER, "source_model" TEXT, "success_count" INTEGER DEFAULT 0, "fail_count" INTEGER DEFAULT 0, "total_latency_ms" INTEGER DEFAULT 0, "total_cost" DOUBLE PRECISION DEFAULT 0, "total_input_tokens" INTEGER DEFAULT 0, "last_used_at" TEXT, "last_selected_at" TEXT, "last_fail_at" TEXT, "consecutive_fail_count" INTEGER NOT NULL DEFAULT 0, "cooldown_level" INTEGER NOT NULL DEFAULT 0, "cooldown_until" TEXT, "created_at" TEXT DEFAULT CURRENT_TIMESTAMP, "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP)',
        'CREATE UNIQUE INDEX IF NOT EXISTS "route_channel_stat_snapshots_identity_unique" ON "route_channel_stat_snapshots" ("identity_key")',
        'CREATE INDEX IF NOT EXISTS "route_channel_stat_snapshots_model_pattern_idx" ON "route_channel_stat_snapshots" ("model_pattern")',
        'CREATE INDEX IF NOT EXISTS "route_channel_stat_snapshots_account_id_idx" ON "route_channel_stat_snapshots" ("account_id")',
        'CREATE INDEX IF NOT EXISTS "route_channel_stat_snapshots_token_id_idx" ON "route_channel_stat_snapshots" ("token_id")',
        'CREATE INDEX IF NOT EXISTS "route_channel_stat_snapshots_oauth_route_unit_id_idx" ON "route_channel_stat_snapshots" ("oauth_route_unit_id")',
        'ALTER TABLE "token_routes" ADD COLUMN "display_name" TEXT',
        'ALTER TABLE "token_routes" ADD COLUMN "display_icon" TEXT',
        'ALTER TABLE "token_routes" ADD COLUMN "route_mode" TEXT DEFAULT \'pattern\'',
        'ALTER TABLE "token_routes" ADD COLUMN "decision_snapshot" TEXT',
        'ALTER TABLE "token_routes" ADD COLUMN "decision_refreshed_at" TEXT',
        'ALTER TABLE "token_routes" ADD COLUMN "routing_strategy" TEXT DEFAULT \'weighted\'',
        'ALTER TABLE "route_channels" ADD COLUMN "source_model" TEXT',
        'ALTER TABLE "route_channels" ADD COLUMN "last_selected_at" TEXT',
        'ALTER TABLE "route_channels" ADD COLUMN "consecutive_fail_count" INTEGER NOT NULL DEFAULT 0',
        'ALTER TABLE "route_channels" ADD COLUMN "cooldown_level" INTEGER NOT NULL DEFAULT 0',
        'ALTER TABLE "route_channels" ADD COLUMN "total_input_tokens" INTEGER DEFAULT 0',
        'ALTER TABLE "route_channels" ADD COLUMN "image_upscale_enabled" BOOLEAN DEFAULT FALSE',
      ],
    },
    {
      dialect: 'mysql' as const,
      expectedSql: [
        'CREATE TABLE IF NOT EXISTS `route_group_sources` (`id` int AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_route_id` int NOT NULL, `source_route_id` int NOT NULL, CONSTRAINT `route_group_sources_group_route_id_token_routes_id_fk` FOREIGN KEY (`group_route_id`) REFERENCES `token_routes`(`id`) ON DELETE cascade, CONSTRAINT `route_group_sources_source_route_id_token_routes_id_fk` FOREIGN KEY (`source_route_id`) REFERENCES `token_routes`(`id`) ON DELETE cascade)',
        'CREATE UNIQUE INDEX IF NOT EXISTS `route_group_sources_group_source_unique` ON `route_group_sources` (`group_route_id`,`source_route_id`)',
        'CREATE INDEX IF NOT EXISTS `route_group_sources_source_route_id_idx` ON `route_group_sources` (`source_route_id`)',
        'CREATE TABLE IF NOT EXISTS `route_channel_stat_snapshots` (`id` int AUTO_INCREMENT NOT NULL PRIMARY KEY, `identity_key` text NOT NULL, `model_pattern` text NOT NULL, `account_id` int NOT NULL, `token_id` int, `oauth_route_unit_id` int, `source_model` text, `success_count` int DEFAULT 0, `fail_count` int DEFAULT 0, `total_latency_ms` int DEFAULT 0, `total_cost` double DEFAULT 0, `total_input_tokens` int DEFAULT 0, `last_used_at` text, `last_selected_at` text, `last_fail_at` text, `consecutive_fail_count` int NOT NULL DEFAULT 0, `cooldown_level` int NOT NULL DEFAULT 0, `cooldown_until` text, `created_at` text DEFAULT (CURRENT_TIMESTAMP), `updated_at` text DEFAULT (CURRENT_TIMESTAMP))',
        'CREATE UNIQUE INDEX IF NOT EXISTS `route_channel_stat_snapshots_identity_unique` ON `route_channel_stat_snapshots` (`identity_key`(255))',
        'CREATE INDEX IF NOT EXISTS `route_channel_stat_snapshots_model_pattern_idx` ON `route_channel_stat_snapshots` (`model_pattern`(255))',
        'CREATE INDEX IF NOT EXISTS `route_channel_stat_snapshots_account_id_idx` ON `route_channel_stat_snapshots` (`account_id`)',
        'CREATE INDEX IF NOT EXISTS `route_channel_stat_snapshots_token_id_idx` ON `route_channel_stat_snapshots` (`token_id`)',
        'CREATE INDEX IF NOT EXISTS `route_channel_stat_snapshots_oauth_route_unit_id_idx` ON `route_channel_stat_snapshots` (`oauth_route_unit_id`)',
        'ALTER TABLE `token_routes` ADD COLUMN `display_name` TEXT NULL',
        'ALTER TABLE `token_routes` ADD COLUMN `display_icon` TEXT NULL',
        'ALTER TABLE `token_routes` ADD COLUMN `route_mode` VARCHAR(32) NULL DEFAULT \'pattern\'',
        'ALTER TABLE `token_routes` ADD COLUMN `decision_snapshot` TEXT NULL',
        'ALTER TABLE `token_routes` ADD COLUMN `decision_refreshed_at` TEXT NULL',
        'ALTER TABLE `token_routes` ADD COLUMN `routing_strategy` VARCHAR(32) NULL DEFAULT \'weighted\'',
        'ALTER TABLE `route_channels` ADD COLUMN `source_model` TEXT NULL',
        'ALTER TABLE `route_channels` ADD COLUMN `last_selected_at` TEXT NULL',
        'ALTER TABLE `route_channels` ADD COLUMN `consecutive_fail_count` INT NOT NULL DEFAULT 0',
        'ALTER TABLE `route_channels` ADD COLUMN `cooldown_level` INT NOT NULL DEFAULT 0',
        'ALTER TABLE `route_channels` ADD COLUMN `total_input_tokens` INT DEFAULT 0',
        'ALTER TABLE `route_channels` ADD COLUMN `image_upscale_enabled` BOOLEAN DEFAULT FALSE',
      ],
    },
  ])('adds missing route grouping columns for $dialect', async ({ dialect, expectedSql }) => {
    const { inspector, executedSql } = createInspector(dialect);

    await ensureRouteGroupingSchemaCompatibility(inspector);

    expect(executedSql).toEqual(expectedSql);
  });

  it('skips existing columns', async () => {
    const { inspector, executedSql } = createInspector('postgres', {
      existingColumnsByTable: {
        token_routes: ['display_name', 'display_icon', 'route_mode', 'decision_snapshot', 'decision_refreshed_at', 'routing_strategy'],
        route_channels: [
          'source_model',
          'last_selected_at',
          'consecutive_fail_count',
          'cooldown_level',
          'total_input_tokens',
          'image_upscale_enabled',
        ],
      },
      existingTables: ['token_routes', 'route_channels', 'route_group_sources', 'route_channel_stat_snapshots'],
    });

    await ensureRouteGroupingSchemaCompatibility(inspector);

    expect(executedSql).toEqual([]);
  });
});
