import { describe, expect, it } from 'vitest';
import { ensureSiteSchemaCompatibility, type SiteSchemaInspector } from './siteSchemaCompatibility.js';

function createInspector(
  dialect: SiteSchemaInspector['dialect'],
  options?: {
    hasSitesTable?: boolean;
    existingTables?: string[];
    existingColumns?: string[];
  },
) {
  const executedSql: string[] = [];
  const hasSitesTable = options?.hasSitesTable ?? true;
  const existingTables = new Set(options?.existingTables ?? []);
  const existingColumns = new Set(options?.existingColumns ?? []);

  const inspector: SiteSchemaInspector = {
    dialect,
    async tableExists(table) {
      if (table === 'sites') return hasSitesTable;
      return existingTables.has(table);
    },
    async columnExists(table, column) {
      return table === 'sites' && existingColumns.has(column);
    },
    async execute(sqlText) {
      executedSql.push(sqlText);
    },
  };

  return { inspector, executedSql };
}

describe('ensureSiteSchemaCompatibility', () => {
  it.each([
    {
      dialect: 'sqlite' as const,
      expectedSql: [
        'ALTER TABLE sites ADD COLUMN proxy_url text;',
        'ALTER TABLE sites ADD COLUMN use_system_proxy integer DEFAULT 0;',
        'UPDATE sites SET use_system_proxy = 0 WHERE use_system_proxy IS NULL;',
        'ALTER TABLE sites ADD COLUMN custom_headers text;',
        'ALTER TABLE sites ADD COLUMN external_checkin_url text;',
        'ALTER TABLE sites ADD COLUMN global_weight real DEFAULT 1;',
        'UPDATE sites SET global_weight = 1 WHERE global_weight IS NULL OR global_weight <= 0;',
        'ALTER TABLE sites ADD COLUMN recharge_ratio real NOT NULL DEFAULT 1;',
        'UPDATE sites SET recharge_ratio = 1 WHERE recharge_ratio IS NULL OR recharge_ratio <= 0;',
        'CREATE TABLE IF NOT EXISTS site_api_endpoints (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, site_id integer NOT NULL REFERENCES sites(id) ON DELETE cascade, url text NOT NULL, enabled integer DEFAULT 1, sort_order integer DEFAULT 0, cooldown_until text, last_selected_at text, last_failed_at text, last_failure_reason text, created_at text DEFAULT (datetime(\'now\')), updated_at text DEFAULT (datetime(\'now\')));',
        'CREATE UNIQUE INDEX IF NOT EXISTS site_api_endpoints_site_url_unique ON site_api_endpoints (site_id, url);',
        'CREATE INDEX IF NOT EXISTS site_api_endpoints_site_enabled_sort_idx ON site_api_endpoints (site_id, enabled, sort_order);',
        'CREATE INDEX IF NOT EXISTS site_api_endpoints_site_cooldown_idx ON site_api_endpoints (site_id, cooldown_until);',
        'CREATE TABLE IF NOT EXISTS site_disabled_models (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, site_id integer NOT NULL REFERENCES sites(id) ON DELETE cascade, model_name text NOT NULL, created_at text DEFAULT (datetime(\'now\')));',
        'CREATE UNIQUE INDEX IF NOT EXISTS site_disabled_models_site_model_unique ON site_disabled_models (site_id, model_name);',
        'CREATE INDEX IF NOT EXISTS site_disabled_models_site_id_idx ON site_disabled_models (site_id);',
      ],
    },
    {
      dialect: 'postgres' as const,
      expectedSql: [
        'ALTER TABLE "sites" ADD COLUMN "proxy_url" TEXT',
        'ALTER TABLE "sites" ADD COLUMN "use_system_proxy" BOOLEAN DEFAULT FALSE',
        'UPDATE "sites" SET "use_system_proxy" = FALSE WHERE "use_system_proxy" IS NULL',
        'ALTER TABLE "sites" ADD COLUMN "custom_headers" TEXT',
        'ALTER TABLE "sites" ADD COLUMN "external_checkin_url" TEXT',
        'ALTER TABLE "sites" ADD COLUMN "global_weight" DOUBLE PRECISION DEFAULT 1',
        'UPDATE "sites" SET "global_weight" = 1 WHERE "global_weight" IS NULL OR "global_weight" <= 0',
        'ALTER TABLE "sites" ADD COLUMN "recharge_ratio" DOUBLE PRECISION NOT NULL DEFAULT 1',
        'UPDATE "sites" SET "recharge_ratio" = 1 WHERE "recharge_ratio" IS NULL OR "recharge_ratio" <= 0',
        'CREATE TABLE IF NOT EXISTS "site_api_endpoints" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "site_id" INTEGER NOT NULL REFERENCES "sites"("id") ON DELETE CASCADE, "url" TEXT NOT NULL, "enabled" BOOLEAN DEFAULT TRUE, "sort_order" INTEGER DEFAULT 0, "cooldown_until" TEXT, "last_selected_at" TEXT, "last_failed_at" TEXT, "last_failure_reason" TEXT, "created_at" TEXT DEFAULT to_char(timezone(\'UTC\', CURRENT_TIMESTAMP), \'YYYY-MM-DD HH24:MI:SS\'), "updated_at" TEXT DEFAULT to_char(timezone(\'UTC\', CURRENT_TIMESTAMP), \'YYYY-MM-DD HH24:MI:SS\'))',
        'CREATE UNIQUE INDEX IF NOT EXISTS "site_api_endpoints_site_url_unique" ON "site_api_endpoints" ("site_id", "url")',
        'CREATE INDEX IF NOT EXISTS "site_api_endpoints_site_enabled_sort_idx" ON "site_api_endpoints" ("site_id", "enabled", "sort_order")',
        'CREATE INDEX IF NOT EXISTS "site_api_endpoints_site_cooldown_idx" ON "site_api_endpoints" ("site_id", "cooldown_until")',
        'CREATE TABLE IF NOT EXISTS "site_disabled_models" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "site_id" INTEGER NOT NULL REFERENCES "sites"("id") ON DELETE CASCADE, "model_name" TEXT NOT NULL, "created_at" TEXT)',
        'CREATE UNIQUE INDEX IF NOT EXISTS "site_disabled_models_site_model_unique" ON "site_disabled_models" ("site_id", "model_name")',
        'CREATE INDEX IF NOT EXISTS "site_disabled_models_site_id_idx" ON "site_disabled_models" ("site_id")',
      ],
    },
    {
      dialect: 'mysql' as const,
      expectedSql: [
        'ALTER TABLE `sites` ADD COLUMN `proxy_url` TEXT NULL',
        'ALTER TABLE `sites` ADD COLUMN `use_system_proxy` BOOLEAN DEFAULT FALSE',
        'UPDATE `sites` SET `use_system_proxy` = FALSE WHERE `use_system_proxy` IS NULL',
        'ALTER TABLE `sites` ADD COLUMN `custom_headers` TEXT NULL',
        'ALTER TABLE `sites` ADD COLUMN `external_checkin_url` TEXT NULL',
        'ALTER TABLE `sites` ADD COLUMN `global_weight` DOUBLE DEFAULT 1',
        'UPDATE `sites` SET `global_weight` = 1 WHERE `global_weight` IS NULL OR `global_weight` <= 0',
        'ALTER TABLE `sites` ADD COLUMN `recharge_ratio` DOUBLE NOT NULL DEFAULT 1',
        'UPDATE `sites` SET `recharge_ratio` = 1 WHERE `recharge_ratio` IS NULL OR `recharge_ratio` <= 0',
        'CREATE TABLE IF NOT EXISTS `site_api_endpoints` (`id` INT AUTO_INCREMENT PRIMARY KEY, `site_id` INT NOT NULL, `url` TEXT NOT NULL, `enabled` BOOLEAN DEFAULT TRUE, `sort_order` INT DEFAULT 0, `cooldown_until` VARCHAR(191) NULL, `last_selected_at` VARCHAR(191) NULL, `last_failed_at` VARCHAR(191) NULL, `last_failure_reason` TEXT NULL, `created_at` VARCHAR(191) DEFAULT (DATE_FORMAT(NOW(), \'%Y-%m-%d %H:%i:%s\')), `updated_at` VARCHAR(191) DEFAULT (DATE_FORMAT(NOW(), \'%Y-%m-%d %H:%i:%s\')), CONSTRAINT `site_api_endpoints_site_fk` FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON DELETE CASCADE)',
        'CREATE UNIQUE INDEX `site_api_endpoints_site_url_unique` ON `site_api_endpoints` (`site_id`, `url`(191))',
        'CREATE INDEX `site_api_endpoints_site_enabled_sort_idx` ON `site_api_endpoints` (`site_id`, `enabled`, `sort_order`)',
        'CREATE INDEX `site_api_endpoints_site_cooldown_idx` ON `site_api_endpoints` (`site_id`, `cooldown_until`(191))',
        'CREATE TABLE IF NOT EXISTS `site_disabled_models` (`id` INT AUTO_INCREMENT PRIMARY KEY, `site_id` INT NOT NULL, `model_name` VARCHAR(191) NOT NULL, `created_at` TEXT NULL, CONSTRAINT `site_disabled_models_site_fk` FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON DELETE CASCADE)',
        'CREATE UNIQUE INDEX `site_disabled_models_site_model_unique` ON `site_disabled_models` (`site_id`, `model_name`(191))',
        'CREATE INDEX `site_disabled_models_site_id_idx` ON `site_disabled_models` (`site_id`)',
      ],
    },
  ])('adds missing site proxy columns for $dialect', async ({ dialect, expectedSql }) => {
    const { inspector, executedSql } = createInspector(dialect);

    await ensureSiteSchemaCompatibility(inspector);

    expect(executedSql).toEqual(expectedSql);
  });

  it('skips schema changes when sites table does not exist', async () => {
    const { inspector, executedSql } = createInspector('postgres', { hasSitesTable: false });

    await ensureSiteSchemaCompatibility(inspector);

    expect(executedSql).toEqual([]);
  });

  it('does not recreate site_disabled_models when it already exists', async () => {
    const { inspector, executedSql } = createInspector('mysql', {
      existingTables: ['site_disabled_models'],
    });

    await ensureSiteSchemaCompatibility(inspector);

    expect(executedSql).not.toContain('CREATE TABLE IF NOT EXISTS `site_disabled_models` (`id` INT AUTO_INCREMENT PRIMARY KEY, `site_id` INT NOT NULL, `model_name` VARCHAR(191) NOT NULL, `created_at` TEXT NULL, CONSTRAINT `site_disabled_models_site_fk` FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON DELETE CASCADE)');
  });
});
